### ISSUE TITLE
Dependency problem with fixed resource order for creation and deletion

### ISSUE THREAD

**Issue by fgimenez** [giantswarm/operatorkit#139]
During the aws-operator migration to CloudFormation based templates we are finding some dependency issues because of the order in which the resources are being managed. 

We have a legacy resource that creates the AWS components imperatively (the current production version of the operator), the basic components are created first and the components that depend on those are created next. Now we have defined a Cloudformation resource, and we are porting components gradually from the legacy resource to the CloudFormation resource, starting from the "most dependent" (least basic) ones. In the resources slice passed to the router, the CloudFormation resource is declared after the legacy resource.

This worked well until we try to port a resource that has a dependency on AWS side. For instance, a NAT gateway depends on a subnet. If we move the NAT gateway from legacy to CF things work well on creation, (the order in which resources are managed is first legacy, then CF) but not on deletion, when we try to delete the subnet on legacy we can't because the gateway is there until CF is processed. This is just an example, happens the same with many other related components. If we start porting the most basic components, we would need to reverse the order of the resources slice (first CloudFormation, then legacy), and again, this would work well on creation but not on deletion (we could not, for instance, delete the CF stack including a VPC if there are still instances attached to it).

So, would it be possible to have a different order in which resources are managed for creation and for deletion? IMO this could solve this specific problem (only two resources related in a very specific, kind of linear way), not sure if it would solve more complex relationships between resources, let me know WDYT.

**Comment by xh3b4sd** [comment]
Assuming this is stale I just close it. Feel free to reopen.
