### ISSUE TITLE
create BaseResource struct

### ISSUE THREAD

**Issue by kopiczko** [giantswarm/operatorkit#26]
```
type BaseResource {
   metav1.TypeMeta `json:",inline"`
   Metadata    metav1.ObjectMeta `json:"metadata,omitempty"`
   Spec          BaseSpec
}
 
type BaseResourceList {
	metav1.TypeMeta `json:",inline"`
	Metadata metav1.ListMeta `json:"metadata,omitempty"`
	Items []BaseResource `json:"items"`
}
```

Taken from https://docs.google.com/document/d/1NJhFcNezJyLM952eaYVcdfIQFQYWsAx4oTaA82-Frdk/edit#

We should add `yaml` support, because of encoding errors.

**Comment by MarcelMue** [comment]
We would have to make the embedding inline, which would screw with our current setup.

**Comment by xh3b4sd** [comment]
Lets make sure to communicate this with the guys who created the original proposal.
