### ISSUE TITLE
Monitor kubernetes events latency

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/operatorkit#3]
We had an issue where an event for an operator was seriously delayed (> 20 minutes).

It would be very useful for system stability to expose rates of events being listwatched by operators, so we can alert on it.

e.g: a certain operator is expected to get x events per second. if this drops majorly, it implies system issues.

**Comment by JosephSalisbury** [comment]
@xh3b4sd from our discussion today

**Comment by xh3b4sd** [comment]
I think in the case that we experienced it would be good to monitor the time it takes for events to flow between producers and consumers. For instance we could apply some creation timestamp to all TPOs via metadata and instrument these in the consumers via operatorkit. That way we would definitely know exact delays and could visualise percentiles for them. 

Note that I put this issue into the operator board so we can prioritise it in our next board sync.

**Comment by xh3b4sd** [comment]
Is this feasible to pursue still? I like the idea but it seems the effort is quite big. We would need to store information about which TPO was seen at which point in time and alert accordingly. Should we keep the issue or close it? AFAIK we did not have a lot of problems with the described issue.

**Comment by JosephSalisbury** [comment]
Yeah, I think we saw this once, and never saw it again. Bye!
