### ISSUE TITLE
Extend OperatorKit TPR client to support all CRUD actions

### ISSUE THREAD

**Issue by rossf7** [giantswarm/operatorkit#32]
Currently, we just support create. It would be useful to support all CRUD actions for managing TPOs.

**Comment by xh3b4sd** [comment]
What do we have to spec here? I would move this to backlog.

**Comment by xh3b4sd** [comment]
Or is the interface unclear?

**Comment by rossf7** [comment]
I think it can move to backlog.

**Comment by xh3b4sd** [comment]
Moved to backlog.

**Comment by xh3b4sd** [comment]
This is fixed by the new CRD package. See https://github.com/giantswarm/operatorkit/tree/19bd080d499095a136c13030d0a0219a8096b255/crd. There are the following methods now. 

```
ListEndpoint() string
ResourceEndpoint(name string) string
WatchEndpoint() string
```
