### ISSUE TITLE
Discuss: Using reconciler framework in AWS and Azure operators

### ISSUE THREAD

**Issue by rossf7** [giantswarm/operatorkit#43]
The `aws-operator` currently has its own [resources](https://github.com/giantswarm/aws-operator/tree/master/resources) implementation. Adapting this to use the `operatorkit` framework would standardise our operators.

The main issues I see are.

## Sequence of resources

For AWS we need to create 15 resources in sequence. Either the framework needs to handle the sequence or each resource needs to check all its dependencies exist before creation. The Retry logic can be used to retry until the dependencies exist. But checking for all dependencies could be cumbersome.

## Handling IDs generated by AWS

We try to identify resources with predictable names including the unique cluster ID. But several resources like VPC need to be referenced by AWS assigned IDs.

These IDs are needed when creating later resources. e.g Internet Gateway. To handle this a resource would need to check the dependency exists and get its ID. We usually tag AWS resources with the cluster ID so this is possible.

## Higher level tools

On AWS we could reduce the number of resources needed by using Cloud Formation stacks. The resource would reconcile the state from the cluster custom object to the CF stack.

On Azure this doesn't look possible because Resource Manager templates only support provisioning not updates. So we'll need to create granular resources with the Azure Go SDK. As we do in `aws-operator` currently.

**Comment by rossf7** [comment]
@xh3b4sd @kopiczko here is my thinking on using the reconciler in `aws-operator`. I think it's important to decide the direction we want to go with for `azure-operator`.

WDYT?

**Comment by xh3b4sd** [comment]
In general I think our motivation should be to use the reconciliation framework. If it is not sufficient we should work on making it sufficient. 

Towards `Sequence of resources`, the order of resources being processed is deterministic. Resources are processed sequentially as configured. As a random brainwave we could provide an async resource implementation that executes all configured resources asynchronously. Anyway, in case multiple resources rely on the same dependency, this dependency should be covered by a resource which is executed beforehand. This dependency resource can then make use of a common service package which provides primitives to manage the actual resource. The primitives of the common service package can then also be used in upcoming resources where the existence of the dependency resource can be checked the its actual data can be fetched. 

Towards `Handling IDs generated by AWS`, if I get this right this is also the responsibility of the common service packages the operator provides. 

Towards `Higher level tools`, we should use them where possible. Using cloudformation in AWS would be cool. I am just wondering if there is any benefit of not using cloudformation. If there is any benefit, we should maybe provide both ways. We could make the use of certain primitives configurable and process resources accordingly. Towards Azure we apparently only have the option to manage the resources in a fine grained way.

**Comment by kopiczko** [comment]
> These IDs are needed when creating later resources. e.g Internet Gateway. To handle this a resource would need to check the dependency exists and get its ID.

I think this is requirement, no matter if the framework is used or not. Otherwise I don't see a way to reconcile properly.

Say Internet Gateway is missing, but dependencies are there during the operator event. We have to reuse the dependencies, and not create a new ones just to get new IDs.

Also we have to be able to update a particular resource on TPO update.


> Higher level tools

I think we agree there the idea is good.

But:

* not possible to use RM in Azure ATM (updates missing)
* I tried CF some time ago (couple of months); back then I didn't find a good way to verify if CF run was applied

**Comment by rossf7** [comment]
For 'Sequence of resources' an async resource implementation could be useful. Several of the AWS resources we need to create are eventually consistent. Creating these in parallel could reduce the time taken to process a cluster.

I agree `Handling the IDs` is a requirement anyway. For resources like VPC where we can't control the name we can tag them and check for the tag. Creating the resources is idempotent but as we add update support this will need to be added to the service primitives.

For 'Higher level tools' we have a specific requirement for Cloud Formation. This is because you can't trigger a rolling update via the `autoscaling` API. It can only be done via Cloud Formation. 

There is also a wish to use higher level tools but it's a tradeoff. We'll need to check the status of the CF stack but it could become more difficult to diagnose problems. Also rather than having service primitives in Go the Cloud Formation templates will need to be modified.

Plus yes we can't use RM in Azure until updates are ready. So the operators will start to diverge. 

On Cloud Formation I think we need it for rolling updates of the workers for  AMI, cloudconfig etc But we don't need to move all the existing resources to it. We can see how much it helps.

**Comment by xh3b4sd** [comment]
> Plus yes we can't use RM in Azure until updates are ready. So the operators will start to diverge.

- I got lost here. What is `RM`? 
- Why will operators diverge?

**Comment by rossf7** [comment]
RM is Azure Resource Manager.  It's the Azure equivalent of Cloud Formation and what Azure Container Service uses to create k8s clusters.

The issue is at the moment is only supports provisioning and not updates. So the diverging is we can only use a higher level tool on AWS.

**Comment by kopiczko** [comment]
> On Cloud Formation I think we need it for rolling updates of the workers for AMI, cloudconfig etc But we don't need to move all the existing resources to it. We can see how much it helps.

I think it's a way to go ATM. It's also easy to verify if CF succeeded by just checking if AMI version is the desired one.

**Comment by xh3b4sd** [comment]
I see. I think the bottom line is we should go with the reconciliation framework. Everything else is about implementation details of the specific operator.

**Comment by rossf7** [comment]
I think we can go with the reconciliation framework for `azure-operator`.  As we need to define a structure for its resources including the Azure primitives. @kopiczko Do you agree or do you want to discuss more?

For `aws-operator` adapting it to use the framework is a bigger job. I'd like to see how it works out in `azure-operator` and if we need to make any extensions to the framework.

**Comment by xh3b4sd** [comment]
I know the migration is a bigger part. Same for KVM. I implemented a legacy resource in the kvm-operator that executes the old logic. Using this it should be easier to rewrite the codebase. We can add a new resource and remove the related old code from the legacy resource. This makes the migration path more graceful. See https://github.com/giantswarm/kvm-operator/tree/88211939021750f30fb6fd7fd2ad45511b674cde/service/resource/legacy. I am also aware that we cannot rewrite everything at once. Lets get our hands dirty and see how it goes. Then we iterate.

**Comment by xh3b4sd** [comment]
Assuming this is stale I just close it. Feel free to reopen.
