### ISSUE TITLE
emitted metrics cause false positive alerts if no CR exists

### ISSUE THREAD

**Issue by xh3b4sd** [giantswarm/operatorkit#518]
We fire `OperatorNotReconciling` alerts if operators get stuck. Though a common false positive is now that these alerts fire if there is no CR to be reconciled. Metrics are emitted in `Reconcile`. That design is somehow broken. 

https://github.com/giantswarm/operatorkit/blob/df9c6fce67f041b1532ca93f0c5dced789a5b129/pkg/controller/controller.go#L325-L327

/cc @giantswarm/sig-operator

**Comment by yulianedyalkova** [comment]
I _think_ the [alert](https://github.com/giantswarm/g8s-prometheus/blob/929956bfab48130ac247bb3f724f5cd89ed00175/helm/g8s-prometheus/prometheus-rules/operatorkit.rules.yml#L210) fires only when there are no `operatorkit_controller_event_count` events for an operator BUT it has objects to reconcile (there are `operatorkit_controller_creation_timestamp` or `operatorkit_controller_deletion_timestamp` events). If you're getting false positives, it might be related to the bug discovered [here](https://github.com/giantswarm/giantswarm/issues/14653).

**Comment by xh3b4sd** [comment]
Interesting, I checked for `last_reconciled` being used and cannot find any reference. Is it then that `lastReconciledGauge` is a relict of the past? I reckon the alerts I saw for false positives are still due to old versions. In my case release `v11.6.x`.

**Comment by tfussell** [comment]
This may no longer be an issue. If someone encounters it, please bring it up with the SIG.
